DROP TABLE AliasPartIndex
DROP TABLE AutoRoutePartIndex
DROP TABLE ContainedPartIndex
DROP TABLE ContentItemIndex
DROP TABLE DeploymentPlanIndex
DROP TABLE Identifiers
DROP TABLE IndexingTask
DROP TABLE LayerMetadataIndex
DROP TABLE OfferIndex
DROP TABLE PaymentIndex
DROP TABLE PersonPartIndex
DROP TABLE TaxonomyIndex
DROP TABLE UserByClaimIndex
DROP TABLE UserByLoginInfoIndex
DROP TABLE UserByRoleNameIndex_Document
DROP TABLE UserByRoleNameIndex
DROP TABLE UserIndex
DROP TABLE UserPickerFieldIndex
DROP TABLE WorkflowBlockingActivitiesIndex
DROP TABLE WorkflowIndex
DROP TABLE WorkflowTypeIndex
DROP TABLE WorkflowTypeStartActivitiesIndex
DROP TABLE DashboardPartIndex
DROP TABLE Document